#!/usr/bin/env zsh

set -e

un-tar  () { tar -xvf "$1" }
un-gz   () { gunzip "$1" }
un-bz2  () { bunzip2 "$1" }


# decompress archive
un-tar SAT-Race-2008-CNF.tar
un-tar SAT-Race_TS_1.tgz
un-tar SAT-Race_TS_2.tgz

# decompress gzipped CNF files
un-gz cnf/goldb-heqc-x1mul.cnf.gz
un-gz cnf/velev-fvp-sat-3.0-b18.cnf.gz
un-gz cnf/simon-s03-w08-15.cnf.gz
un-gz cnf/ibm-2002-25r-k10.cnf.gz
un-gz cnf/velev-vliw-uns-2.0-iq2.cnf.gz
un-gz cnf/manol-pipe-g8nidw.cnf.gz
un-gz cnf/schup-l2s-bc56s-1-k391.cnf.gz
un-gz cnf/manol-pipe-c8nidw.cnf.gz
un-gz cnf/post-c32s-col400-16.cnf.gz
un-gz cnf/cmu-bmc-longmult13.cnf.gz
un-gz cnf/een-tip-sat-vis-eisen.cnf.gz
un-gz cnf/ibm-2004-1_11-k80.cnf.gz
un-gz cnf/mizh-sha0-36-1.cnf.gz
un-gz cnf/ibm-2004-01-k90.cnf.gz
un-gz cnf/mizh-sha0-35-3.cnf.gz
un-gz cnf/manol-pipe-f7nidw.cnf.gz
un-gz cnf/manol-pipe-c10nid_i.cnf.gz
un-gz cnf/anbul-dated-5-15-u.cnf.gz
un-gz cnf/ibm-2004-3_02_3-k95.cnf.gz
un-gz cnf/ibm-2004-23-k100.cnf.gz
un-gz cnf/simon-s02-f2clk-50.cnf.gz
un-gz cnf/een-pico-prop05-75.cnf.gz
un-gz cnf/ibm-2002-22r-k80.cnf.gz
un-gz cnf/ibm-2002-11r1-k45.cnf.gz
un-gz cnf/een-pico-prop00-75.cnf.gz
un-gz cnf/cmu-bmc-longmult15.cnf.gz
un-gz cnf/post-c32s-ss-8.cnf.gz
un-gz cnf/velev-vliw-uns-4.0-9-i1.cnf.gz
un-gz cnf/aloul-chnl11-13.cnf.gz
un-gz cnf/mizh-sha0-35-4.cnf.gz
un-gz cnf/palac-uts-l06-ipc5-h34.cnf.gz
un-gz cnf/post-cbmc-aes-ee-r2.cnf.gz
un-gz cnf/velev-vliw-uns-4.0-9.cnf.gz
un-gz cnf/manol-pipe-c6bidw_i.cnf.gz
un-gz cnf/fuhs-aprove-15.cnf.gz
un-gz cnf/ibm-2002-20r-k75.cnf.gz
un-gz cnf/jarvi-eq-atree-9.cnf.gz
un-gz cnf/post-cbmc-aes-d-r2.cnf.gz
un-gz cnf/simon-s03-fifo8-400.cnf.gz
un-gz cnf/mizh-md5-48-5.cnf.gz
un-gz cnf/een-tip-sat-nusmv-t5.B.cnf.gz
un-gz cnf/vange-col-abb313GPIA-9-c.cnf.gz
un-gz cnf/manol-pipe-g10bid_i.cnf.gz
un-gz cnf/hoons-vbmc-lucky7.cnf.gz
un-gz cnf/anbul-part-10-15-s.cnf.gz
un-gz cnf/mizh-md5-47-5.cnf.gz
un-gz cnf/simon-s02b-r4b1k1.1.cnf.gz
un-gz cnf/ibm-2002-18r-k90.cnf.gz
un-gz cnf/ibm-2002-23r-k90.cnf.gz
un-gz cnf/ibm-2004-29-k25.cnf.gz
un-gz cnf/mizh-md5-48-2.cnf.gz
un-gz cnf/goldb-heqc-frg1mul.cnf.gz
un-gz cnf/palac-sn7-ipc5-h16.cnf.gz
un-gz cnf/velev-vliw-sat-4.0-b8.cnf.gz
un-gz cnf/babic-dspam-vc973.cnf.gz
un-gz cnf/marijn-philips.cnf.gz
un-gz cnf/ibm-2002-31_1r3-k30.cnf.gz
un-gz cnf/ibm-2002-24r3-k100.cnf.gz
un-gz cnf/velev-engi-uns-1.0-4nd.cnf.gz
un-gz cnf/post-cbmc-zfcp-2.8-u2.cnf.gz
un-gz cnf/mizh-md5-47-3.cnf.gz
un-gz cnf/schup-l2s-abp4-1-k31.cnf.gz
un-bz2 cnf/narain-vpn-clauses-10.cnf.bz2
un-gz cnf/grieu-vmpc-27.cnf.gz
un-gz cnf/schup-l2s-motst-2-k315.cnf.gz
un-gz cnf/post-cbmc-aes-ee-r3.cnf.gz
un-gz cnf/babic-dspam-vc949.cnf.gz
un-gz cnf/ibm-2004-29-k55.cnf.gz
un-gz cnf/velev-vliw-uns-2.0-iq1.cnf.gz
un-gz cnf/mizh-sha0-36-3.cnf.gz
un-gz cnf/velev-vliw-sat-4.0-b4.cnf.gz
un-gz cnf/manol-pipe-g10nid.cnf.gz
un-gz cnf/cmu-bmc-barrel6.cnf.gz
un-gz cnf/manol-pipe-c10nidw.cnf.gz
un-gz cnf/ibm-2004-23-k80.cnf.gz
un-gz cnf/grieu-vmpc-31.cnf.gz
un-gz cnf/narain-vpn-clauses-8.cnf.gz
un-gz cnf/post-cbmc-aes-ele.cnf.gz
un-gz cnf/anbul-part-10-13-s.cnf.gz
un-gz cnf/ibm-2002-29r-k75.cnf.gz
un-gz cnf/goldb-heqc-dalumul.cnf.gz
un-gz cnf/mizh-sha0-36-4.cnf.gz
un-gz cnf/ibm-2002-30r-k85.cnf.gz
un-gz cnf/velev-vliw-uns-2.0-uq5.cnf.gz
un-gz cnf/een-tip-sat-texas-tp-5e.cnf.gz
un-gz cnf/post-c32s-gcdm16-22.cnf.gz
un-gz cnf/manol-pipe-f9b.cnf.gz
un-gz cnf/fuhs-aprove-16.cnf.gz
un-gz cnf/babic-dspam-vc1080.cnf.gz
un-gz cnf/goldb-heqc-alu4mul.cnf.gz
un-gz cnf/simon-s02b-r4b1k1.2.cnf.gz
un-gz cnf/mizh-md5-47-4.cnf.gz
un-gz cnf/post-cbmc-aes-d-r1.cnf.gz
un-gz cnf/maris-s03-gripper11.cnf.gz
un-gz cnf/post-c32s-gcdm16-23.cnf.gz
un-gz cnf/ibm-2002-22r-k60.cnf.gz
un-gz cnf/manol-pipe-c9n_i.cnf.gz
un-gz cnf/ibm-2002-04r-k80.cnf.gz
un-gz cnf/ibm-2002-22r-k75.cnf.gz
un-gz cnf/velev-npe-1.0-9dlx-b71.cnf.gz
un-gz SAT-Race_TS_1/grieu-vmpc-s05-27r.cnf.gz
un-gz SAT-Race_TS_1/manol-pipe-g6bid.cnf.gz
un-gz SAT-Race_TS_1/goldb-heqc-rotmul.cnf.gz
un-gz SAT-Race_TS_1/velev-pipe-uns-1.0-08.cnf.gz
un-gz SAT-Race_TS_1/manol-pipe-g10idw.cnf.gz
un-gz SAT-Race_TS_1/velev-pipe-uns-1.1-07.cnf.gz
un-gz SAT-Race_TS_1/manol-pipe-c6nid_s.cnf.gz
un-gz SAT-Race_TS_1/schup-l2s-s04-abp4.cnf.gz
un-gz SAT-Race_TS_1/velev-pipe-1.1-05.cnf.gz
un-gz SAT-Race_TS_1/velev-eng-uns-1.0-04a.cnf.gz
un-gz SAT-Race_TS_1/velev-pipe-1.0-09.cnf.gz
un-gz SAT-Race_TS_1/velev-vliw-sat-2.0-02.cnf.gz
un-gz SAT-Race_TS_1/manol-pipe-c6id.cnf.gz
un-gz SAT-Race_TS_1/velev-pipe-1.1-03.cnf.gz
un-gz SAT-Race_TS_1/een-tipb-sr06-par1.cnf.gz
un-gz SAT-Race_TS_1/velev-fvp-sat-3.0-12.cnf.gz
un-gz SAT-Race_TS_1/velev-npe-1.0-03.cnf.gz
un-gz SAT-Race_TS_1/manol-pipe-c8b_i.cnf.gz
un-gz SAT-Race_TS_1/stric-bmc-ibm-10.cnf.gz
un-gz SAT-Race_TS_1/goldb-heqc-desmul.cnf.gz
un-gz SAT-Race_TS_1/simon-mixed-s02bis-03.cnf.gz
un-gz SAT-Race_TS_1/hoons-vbmc-s04-05.cnf.gz
un-gz SAT-Race_TS_1/manol-pipe-f6n.cnf.gz
un-gz SAT-Race_TS_1/manol-pipe-c6n.cnf.gz
un-gz SAT-Race_TS_1/manol-pipe-c10ni_s.cnf.gz
un-gz SAT-Race_TS_1/velev-live-sat-1.0-01.cnf.gz
un-gz SAT-Race_TS_1/manol-pipe-c7idw.cnf.gz
un-gz SAT-Race_TS_1/velev-vliw-sat-2.0-04.cnf.gz
un-gz SAT-Race_TS_1/velev-fvp-sat-3.0-07.cnf.gz
un-gz SAT-Race_TS_1/grieu-vmpc-s05-24s.cnf.gz
un-gz SAT-Race_TS_1/velev-sss-1.0-cl.cnf.gz
un-gz SAT-Race_TS_1/velev-vliw-uns-2.0-02.cnf.gz
un-gz SAT-Race_TS_1/manol-pipe-c10b.cnf.gz
un-gz SAT-Race_TS_1/simon-mixed-s02bis-01.cnf.gz
un-gz SAT-Race_TS_1/narai-vpn-10s.cnf.gz
un-gz SAT-Race_TS_1/vange-color-inc-54.cnf.gz
un-gz SAT-Race_TS_1/velev-npe-1.0-02.cnf.gz
un-gz SAT-Race_TS_1/velev-live-sat-1.0-03.cnf.gz
un-gz SAT-Race_TS_1/velev-eng-uns-1.0-04.cnf.gz
un-gz SAT-Race_TS_1/simon-mixed-s02bis-05.cnf.gz
un-gz SAT-Race_TS_1/manol-pipe-f6b.cnf.gz
un-gz SAT-Race_TS_1/manol-pipe-g7n.cnf.gz
un-gz SAT-Race_TS_1/manol-pipe-c7_i.cnf.gz
un-gz SAT-Race_TS_1/stric-bmc-ibm-12.cnf.gz
un-gz SAT-Race_TS_1/velev-pipe-uns-1.1-05.cnf.gz
un-gz SAT-Race_TS_1/manol-pipe-c8n.cnf.gz
un-gz SAT-Race_TS_1/een-tipb-sr06-tc6b.cnf.gz
un-gz SAT-Race_TS_1/velev-pipe-1.0-08.cnf.gz
un-gz SAT-Race_TS_1/manol-pipe-c8_i.cnf.gz
un-gz SAT-Race_TS_1/hoons-vbmc-s04-07.cnf.gz
un-gz SAT-Race_TS_2/velev-pipe-sat-1.1-01.cnf.gz
un-gz SAT-Race_TS_2/velev-pipe-sat-1.1-09.cnf.gz
un-gz SAT-Race_TS_2/velev-pipe-uns-1.1-03.cnf.gz
un-gz SAT-Race_TS_2/schup-l2s-s04s2-09.cnf.gz
un-gz SAT-Race_TS_2/TS2-Solvers2005-results.txt
un-gz SAT-Race_TS_2/manol-pipe-f6i.cnf.gz
un-gz SAT-Race_TS_2/velev-vliw-sat-4.0-03.cnf.gz
un-gz SAT-Race_TS_2/manol-pipe-g8n.cnf.gz
un-gz SAT-Race_TS_2/manol-pipe-c10id_s.cnf.gz
un-gz SAT-Race_TS_2/velev-dlx-uns-1.0-05.cnf.gz
un-gz SAT-Race_TS_2/narai-vpn-sat05-02s.cnf.gz
un-gz SAT-Race_TS_2/manol-pipe-c8b_i.cnf.gz
un-gz SAT-Race_TS_2/miza-sr06-md5-48-01.cnf.gz
un-gz SAT-Race_TS_2/velev-live-2.0-02.cnf.gz
un-gz SAT-Race_TS_2/manol-pipe-c6nidw.cnf.gz
un-gz SAT-Race_TS_2/grieu-vmpc-s05-05s.cnf.gz
un-gz SAT-Race_TS_2/manol-pipe-c7idw_s.cnf.gz
un-gz SAT-Race_TS_2/velev-pipe-uns-1.1-08.cnf.gz
un-gz SAT-Race_TS_2/manol-pipe-f7idw.cnf.gz
un-gz SAT-Race_TS_2/goldb-heqc-i8mul.cnf.gz
un-gz SAT-Race_TS_2/velev-pipe-oun-1.0-04.cnf.gz
un-gz SAT-Race_TS_2/manol-pipe-g8bidw.cnf.gz
un-gz SAT-Race_TS_2/hoons-vbmc-s04-06.cnf.gz
un-gz SAT-Race_TS_2/miza-sr06-sha0-35-03.cnf.gz
un-gz SAT-Race_TS_2/manol-pipe-f6nid.cnf.gz
un-gz SAT-Race_TS_2/manol-pipe-c6idw_s.cnf.gz
un-gz SAT-Race_TS_2/velev-pipe-sat-1.0-03.cnf.gz
un-gz SAT-Race_TS_2/velev-pipe-uns-1.0-14.cnf.gz
un-gz SAT-Race_TS_2/manol-pipe-cha05-143.cnf.gz
un-gz SAT-Race_TS_2/velev-sss-1.0-05.cnf.gz
un-gz SAT-Race_TS_2/manol-pipe-c6bid_i.cnf.gz
un-gz SAT-Race_TS_2/velev-live-sat-1.0-05.cnf.gz
un-gz SAT-Race_TS_2/miza-sr06-md5-47-03.cnf.gz
un-gz SAT-Race_TS_2/manol-pipe-c6b_i.cnf.gz
un-gz SAT-Race_TS_2/simon-mixed-s02bis-05.cnf.gz
un-gz SAT-Race_TS_2/manol-pipe-c6ni_s.cnf.gz
un-gz SAT-Race_TS_2/goldb-heqc-k2mul.cnf.gz
un-gz SAT-Race_TS_2/manol-pipe-c10bi_s.cnf.gz
un-gz SAT-Race_TS_2/een-pico-sr06-pr02-02.cnf.gz
un-gz SAT-Race_TS_2/manol-pipe-c7_i.cnf.gz
un-gz SAT-Race_TS_2/velev-pipe-sat-1.1-03.cnf.gz
un-gz SAT-Race_TS_2/velev-pipe-sat-1.0-01.cnf.gz
un-gz SAT-Race_TS_2/manol-pipe-c10nid_s.cnf.gz
un-gz SAT-Race_TS_2/manol-pipe-g10ni.cnf.gz
un-gz SAT-Race_TS_2/aloul-sr06-chnl10-13.cnf.gz
un-gz SAT-Race_TS_2/velev-pipe-oun-1.1-05.cnf.gz
un-gz SAT-Race_TS_2/schup-l2s-s04-valves.cnf.gz
un-gz SAT-Race_TS_2/narai-vpn-sat05-07.cnf.gz
un-gz SAT-Race_TS_2/manol-pipe-g8b.cnf.gz
un-gz SAT-Race_TS_2/hoons-vbmc-s04-07.cnf.gz
un-gz SAT-Race_TS_2/manol-pipe-cha05-113.cnf.gz
